# GitHub Pages Configuration File

# Title and description
title: My Secure GitHub Pages Site
description: A secure static site hosted on GitHub Pages.

# Enable HTTPS
https: true

# Security headers
headers:
  - key: "Content-Security-Policy"
    value: "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self';"
  - key: "X-Content-Type-Options"
    value: "nosniff"
  - key: "X-Frame-Options"
    value: "DENY"
  - key: "X-XSS-Protection"
    value: "1; mode=block"

# Enable dependabot
dependabot: true